import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'it' | 'sw' | 'de' | 'pt' | 'nl' | 'zh';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.crafts': 'Our Crafts',
    'nav.stories': 'Stories',
    'nav.gifts': 'Gift Ideas',
    'nav.sustainability': 'Sustainability',
    'nav.csr': 'CSR',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.signin': 'Sign in / Register',
    'nav.account': 'Account',
    'nav.welcome': 'Welcome',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.tryAgain': 'Try Again',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    'common.shopNow': 'Shop Now',
    'common.addToCart': 'Add to Cart',
    'common.buyNow': 'Buy Now',
    'common.contactUs': 'Contact Us',
    
    // Pages
    'page.stories.title': 'Artisan Stories',
    'page.stories.subtitle': 'Meet the talented craftspeople preserving African traditions through their art',
    'page.stories.noStories': 'No Stories Available',
    'page.stories.checkBack': 'Check back later for inspiring artisan stories.',
    'page.stories.shareStory': 'Share Your Story',
    'page.stories.shareDescription': 'Are you a skilled artisan with a story to tell? We\'d love to feature your craft and share your journey with our community of art enthusiasts.',
    'page.stories.browseCrafts': 'Browse Crafts',
    'page.stories.readFullStory': 'Read Full Story',
    
    'page.contact.title': 'Contact Us',
    'page.contact.subtitle': 'Get in touch with us for questions about our crafts, custom orders, or artisan collaborations',
    'page.contact.sendMessage': 'Send us a Message',
    'page.contact.getInTouch': 'Get in Touch',
    'page.contact.fullName': 'Full Name',
    'page.contact.emailAddress': 'Email Address',
    'page.contact.subject': 'Subject',
    'page.contact.message': 'Message',
    'page.contact.sendButton': 'Send Message',
    'page.contact.location': 'Our Location',
    'page.contact.phone': 'Phone Number',
    'page.contact.email': 'Email Address',
    'page.contact.hours': 'Business Hours',
    'page.contact.visitWorkshop': 'Visit Our Workshop',
    'page.contact.scheduleVisit': 'Schedule a Visit',
    
    'page.about.title': 'About Things From Africa',
    'page.about.subtitle': 'Preserving traditions, empowering artisans, and sharing the beauty of Africa with the world',
    'page.about.mission': 'Our Mission',
    'page.about.missionText1': 'We are dedicated to preserving Africa\'s rich cultural heritage through authentic handcrafted products. Our mission is to connect skilled artisans with global markets while maintaining the integrity of traditional craftsmanship.',
    'page.about.missionText2': 'Every purchase supports local communities and helps preserve centuries-old techniques passed down through generations.',
    'page.about.meetArtisans': 'Meet Our Artisans',
    'page.about.values': 'Our Values',
    'page.about.authenticity': 'Authenticity',
    'page.about.quality': 'Quality',
    'page.about.community': 'Community',
    'page.about.sustainability': 'Sustainability',
    'page.about.story': 'Our Story',
    'page.about.storyText1': 'Founded in 2015, Malawi Crafts began as a small initiative to help local artisans reach international markets. What started as a passion project has grown into a thriving platform that showcases the incredible talent and creativity of Malawian craftspeople.',
    'page.about.storyText2': 'Today, we work with over 200 artisans across Malawi, from wood carvers in Lilongwe to basket weavers in the northern regions. Each piece tells a story of skill, tradition, and the vibrant culture of the "Warm Heart of Africa."',
    'page.about.storyText3': 'We believe that by sharing these beautiful crafts with the world, we\'re not just selling products – we\'re building bridges between cultures and creating sustainable livelihoods for talented artisans.',
    'page.about.communityImpact': 'Community Impact',
    'page.about.communityText': 'Supporting families and preserving traditional skills in rural communities across Africa.',
    'page.about.globalReach': 'Global Reach',
    'page.about.globalText': 'Connecting African artisans with customers worldwide, sharing our culture globally.',
    'page.about.sustainableFuture': 'Sustainable Future',
    'page.about.sustainableText': 'Creating lasting economic opportunities while respecting our environment and traditions.',
    'page.about.joinJourney': 'Join Our Journey',
    'page.about.joinText': 'Become part of our story by supporting authentic African craftsmanship. Every purchase makes a difference in preserving our cultural heritage and supporting artisan communities.',
    'page.about.shopCrafts': 'Shop Our Crafts',
    'page.about.learnMore': 'Learn More',
    'page.about.artisans': 'Artisans',
    'page.about.regions': 'Regions',
    'page.about.founded': 'Founded',
    'page.about.customers': 'Happy Customers',
    
    'page.crafts.title': 'Our Traditional Crafts',
    'page.crafts.subtitle': 'Discover the rich heritage of African craftsmanship through our diverse collection of traditional arts',
    'page.crafts.authentic': 'Authentic Handmade',
    'page.crafts.sustainable': 'Sustainable Materials',
    'page.crafts.heritage': 'Cultural Heritage',
    'page.crafts.loading': 'Loading our beautiful crafts...',
    'page.crafts.error': 'Unable to load crafts',
    'page.crafts.tryAgain': 'Please try again later',
    'page.crafts.noCrafts': 'No Crafts Available',
    'page.crafts.checkBack': 'Check back later for our beautiful craft collection.',
    'page.crafts.explore': 'Explore Crafts',
    'page.crafts.traditional': 'Traditional',
    'page.crafts.preserving': 'Preserving Cultural Heritage',
    'page.crafts.preservingText': 'Each craft represents centuries of tradition, skill, and cultural identity. By supporting our artisans, you help preserve these invaluable techniques for future generations.',
    'page.crafts.skilledArtisans': 'Skilled Artisans',
    'page.crafts.yearsOfTradition': 'Years of Tradition',
    'page.crafts.authenticHandmade': 'Authentic Handmade',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.shop': 'Tienda',
    'nav.crafts': 'Nuestras Artesanías',
    'nav.stories': 'Historias',
    'nav.gifts': 'Ideas de Regalos',
    'nav.sustainability': 'Sostenibilidad',
    'nav.csr': 'RSC',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    'nav.cart': 'Carrito',
    'nav.signin': 'Iniciar sesión / Registrarse',
    'nav.account': 'Cuenta',
    'nav.welcome': 'Bienvenido',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.tryAgain': 'Intentar de nuevo',
    'common.readMore': 'Leer más',
    'common.learnMore': 'Aprender más',
    'common.viewAll': 'Ver todo',
    'common.shopNow': 'Comprar ahora',
    'common.addToCart': 'Añadir al carrito',
    'common.buyNow': 'Comprar ahora',
    'common.contactUs': 'Contáctanos',
    
    // Pages
    'page.stories.title': 'Historias de Artesanos',
    'page.stories.subtitle': 'Conoce a los talentosos artesanos que preservan las tradiciones africanas a través de su arte',
    'page.stories.noStories': 'No hay historias disponibles',
    'page.stories.checkBack': 'Vuelve más tarde para historias inspiradoras de artesanos.',
    'page.stories.shareStory': 'Comparte tu historia',
    'page.stories.shareDescription': '¿Eres un artesano hábil con una historia que contar? Nos encantaría presentar tu arte y compartir tu viaje con nuestra comunidad de entusiastas del arte.',
    'page.stories.browseCrafts': 'Explorar artesanías',
    'page.stories.readFullStory': 'Leer historia completa',
    
    'page.contact.title': 'Contáctanos',
    'page.contact.subtitle': 'Ponte en contacto con nosotros para preguntas sobre nuestras artesanías, pedidos personalizados o colaboraciones con artesanos',
    'page.contact.sendMessage': 'Envíanos un mensaje',
    'page.contact.getInTouch': 'Ponte en contacto',
    'page.contact.fullName': 'Nombre completo',
    'page.contact.emailAddress': 'Dirección de correo',
    'page.contact.subject': 'Asunto',
    'page.contact.message': 'Mensaje',
    'page.contact.sendButton': 'Enviar mensaje',
    'page.contact.location': 'Nuestra ubicación',
    'page.contact.phone': 'Número de teléfono',
    'page.contact.email': 'Dirección de correo',
    'page.contact.hours': 'Horario comercial',
    'page.contact.visitWorkshop': 'Visita nuestro taller',
    'page.contact.scheduleVisit': 'Programar una visita',
    
    'page.about.title': 'Acerca de Things From Africa',
    'page.about.subtitle': 'Preservando tradiciones, empoderando artesanos y compartiendo la belleza de África con el mundo',
    'page.about.mission': 'Nuestra Misión',
    'page.about.missionText1': 'Nos dedicamos a preservar el rico patrimonio cultural de África a través de productos auténticos hechos a mano. Nuestra misión es conectar artesanos hábiles con mercados globales manteniendo la integridad de la artesanía tradicional.',
    'page.about.missionText2': 'Cada compra apoya a las comunidades locales y ayuda a preservar técnicas centenarias transmitidas de generación en generación.',
    'page.about.meetArtisans': 'Conoce Nuestros Artesanos',
    'page.about.values': 'Nuestros Valores',
    'page.about.authenticity': 'Autenticidad',
    'page.about.quality': 'Calidad',
    'page.about.community': 'Comunidad',
    'page.about.sustainability': 'Sostenibilidad',
    'page.about.story': 'Nuestra Historia',
    'page.about.storyText1': 'Fundada en 2015, Malawi Crafts comenzó como una pequeña iniciativa para ayudar a los artesanos locales a llegar a mercados internacionales. Lo que comenzó como un proyecto de pasión se ha convertido en una plataforma próspera que muestra el increíble talento y creatividad de los artesanos malauíes.',
    'page.about.storyText2': 'Hoy trabajamos con más de 200 artesanos en todo Malawi, desde talladores de madera en Lilongwe hasta tejedores de cestas en las regiones del norte. Cada pieza cuenta una historia de habilidad, tradición y la cultura vibrante del "Corazón Cálido de África".',
    'page.about.storyText3': 'Creemos que al compartir estas hermosas artesanías con el mundo, no solo vendemos productos, sino que construimos puentes entre culturas y creamos medios de vida sostenibles para artesanos talentosos.',
    'page.about.communityImpact': 'Impacto Comunitario',
    'page.about.communityText': 'Apoyando familias y preservando habilidades tradicionales en comunidades rurales de África.',
    'page.about.globalReach': 'Alcance Global',
    'page.about.globalText': 'Conectando artesanos africanos con clientes de todo el mundo, compartiendo nuestra cultura globalmente.',
    'page.about.sustainableFuture': 'Futuro Sostenible',
    'page.about.sustainableText': 'Creando oportunidades económicas duraderas respetando nuestro medio ambiente y tradiciones.',
    'page.about.joinJourney': 'Únete a Nuestro Viaje',
    'page.about.joinText': 'Forma parte de nuestra historia apoyando la artesanía africana auténtica. Cada compra marca la diferencia en preservar nuestro patrimonio cultural y apoyar comunidades artesanales.',
    'page.about.shopCrafts': 'Compra Nuestras Artesanías',
    'page.about.learnMore': 'Aprender Más',
    'page.about.artisans': 'Artesanos',
    'page.about.regions': 'Regiones',
    'page.about.founded': 'Fundada',
    'page.about.customers': 'Clientes Felices',
    
    'page.crafts.title': 'Nuestras Artesanías Tradicionales',
    'page.crafts.subtitle': 'Descubre el rico patrimonio de la artesanía africana a través de nuestra diversa colección de artes tradicionales',
    'page.crafts.authentic': 'Hecho a Mano Auténtico',
    'page.crafts.sustainable': 'Materiales Sostenibles',
    'page.crafts.heritage': 'Patrimonio Cultural',
    'page.crafts.loading': 'Cargando nuestras hermosas artesanías...',
    'page.crafts.error': 'No se pueden cargar las artesanías',
    'page.crafts.tryAgain': 'Por favor, inténtalo de nuevo más tarde',
    'page.crafts.noCrafts': 'No hay artesanías disponibles',
    'page.crafts.checkBack': 'Vuelve más tarde para nuestra hermosa colección de artesanías.',
    'page.crafts.explore': 'Explorar Artesanías',
    'page.crafts.traditional': 'Tradicional',
    'page.crafts.preserving': 'Preservando el Patrimonio Cultural',
    'page.crafts.preservingText': 'Cada artesanía representa siglos de tradición, habilidad e identidad cultural. Al apoyar a nuestros artesanos, ayudas a preservar estas técnicas invaluables para las generaciones futuras.',
    'page.crafts.skilledArtisans': 'Artesanos Hábiles',
    'page.crafts.yearsOfTradition': 'Años de Tradición',
    'page.crafts.authenticHandmade': 'Hecho a Mano Auténtico',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.shop': 'Boutique',
    'nav.crafts': 'Nos Artisanats',
    'nav.stories': 'Histoires',
    'nav.gifts': 'Idées Cadeaux',
    'nav.sustainability': 'Durabilité',
    'nav.csr': 'RSE',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.cart': 'Panier',
    'nav.signin': 'Se connecter / S\'inscrire',
    'nav.account': 'Compte',
    'nav.welcome': 'Bienvenue',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.tryAgain': 'Réessayer',
    'common.readMore': 'Lire plus',
    'common.learnMore': 'En savoir plus',
    'common.viewAll': 'Voir tout',
    'common.shopNow': 'Acheter maintenant',
    'common.addToCart': 'Ajouter au panier',
    'common.buyNow': 'Acheter maintenant',
    'common.contactUs': 'Nous contacter',
    
    // Pages
    'page.stories.title': 'Histoires d\'Artisans',
    'page.stories.subtitle': 'Rencontrez les artisans talentueux qui préservent les traditions africaines à travers leur art',
    'page.stories.noStories': 'Aucune histoire disponible',
    'page.stories.checkBack': 'Revenez plus tard pour des histoires inspirantes d\'artisans.',
    'page.stories.shareStory': 'Partagez votre histoire',
    'page.stories.shareDescription': 'Êtes-vous un artisan qualifié avec une histoire à raconter? Nous aimerions présenter votre art et partager votre parcours avec notre communauté d\'amateurs d\'art.',
    'page.stories.browseCrafts': 'Parcourir les artisanats',
    'page.stories.readFullStory': 'Lire l\'histoire complète',
    
    'page.contact.title': 'Nous contacter',
    'page.contact.subtitle': 'Contactez-nous pour des questions sur nos artisanats, commandes personnalisées ou collaborations avec des artisans',
    'page.contact.sendMessage': 'Envoyez-nous un message',
    'page.contact.getInTouch': 'Entrer en contact',
    'page.contact.fullName': 'Nom complet',
    'page.contact.emailAddress': 'Adresse e-mail',
    'page.contact.subject': 'Sujet',
    'page.contact.message': 'Message',
    'page.contact.sendButton': 'Envoyer le message',
    'page.contact.location': 'Notre emplacement',
    'page.contact.phone': 'Numéro de téléphone',
    'page.contact.email': 'Adresse e-mail',
    'page.contact.hours': 'Heures d\'ouverture',
    'page.contact.visitWorkshop': 'Visitez notre atelier',
    'page.contact.scheduleVisit': 'Planifier une visite',
    
    'page.about.title': 'À propos de Things From Africa',
    'page.about.subtitle': 'Préserver les traditions, autonomiser les artisans et partager la beauté de l\'Afrique avec le monde',
    'page.about.mission': 'Notre Mission',
    'page.about.missionText1': 'Nous nous consacrons à préserver le riche patrimoine culturel de l\'Afrique à travers des produits artisanaux authentiques. Notre mission est de connecter les artisans qualifiés aux marchés mondiaux tout en maintenant l\'intégrité de l\'artisanat traditionnel.',
    'page.about.missionText2': 'Chaque achat soutient les communautés locales et aide à préserver les techniques séculaires transmises de génération en génération.',
    'page.about.meetArtisans': 'Rencontrez Nos Artisans',
    'page.about.values': 'Nos Valeurs',
    'page.about.authenticity': 'Authenticité',
    'page.about.quality': 'Qualité',
    'page.about.community': 'Communauté',
    'page.about.sustainability': 'Durabilité',
    'page.about.story': 'Notre Histoire',
    'page.about.storyText1': 'Fondée en 2015, Malawi Crafts a commencé comme une petite initiative pour aider les artisans locaux à atteindre les marchés internationaux. Ce qui a commencé comme un projet de passion est devenu une plateforme florissante qui met en valeur l\'incroyable talent et créativité des artisans malawiens.',
    'page.about.storyText2': 'Aujourd\'hui, nous travaillons avec plus de 200 artisans à travers le Malawi, des sculpteurs sur bois de Lilongwe aux tisserands de paniers des régions du nord. Chaque pièce raconte une histoire de compétence, de tradition et de la culture vibrante du "Cœur Chaleureux de l\'Afrique".',
    'page.about.storyText3': 'Nous croyons qu\'en partageant ces beaux artisanats avec le monde, nous ne vendons pas seulement des produits – nous construisons des ponts entre les cultures et créons des moyens de subsistance durables pour les artisans talentueux.',
    'page.about.communityImpact': 'Impact Communautaire',
    'page.about.communityText': 'Soutenir les familles et préserver les compétences traditionnelles dans les communautés rurales d\'Afrique.',
    'page.about.globalReach': 'Portée Mondiale',
    'page.about.globalText': 'Connecter les artisans africains avec des clients du monde entier, partager notre culture globalement.',
    'page.about.sustainableFuture': 'Avenir Durable',
    'page.about.sustainableText': 'Créer des opportunités économiques durables tout en respectant notre environnement et nos traditions.',
    'page.about.joinJourney': 'Rejoignez Notre Voyage',
    'page.about.joinText': 'Devenez partie de notre histoire en soutenant l\'artisanat africain authentique. Chaque achat fait une différence dans la préservation de notre patrimoine culturel et le soutien des communautés artisanales.',
    'page.about.shopCrafts': 'Achetez Nos Artisanats',
    'page.about.learnMore': 'En Savoir Plus',
    'page.about.artisans': 'Artisans',
    'page.about.regions': 'Régions',
    'page.about.founded': 'Fondée',
    'page.about.customers': 'Clients Heureux',
    
    'page.crafts.title': 'Nos Artisanats Traditionnels',
    'page.crafts.subtitle': 'Découvrez le riche patrimoine de l\'artisanat africain à travers notre collection diversifiée d\'arts traditionnels',
    'page.crafts.authentic': 'Fait Main Authentique',
    'page.crafts.sustainable': 'Matériaux Durables',
    'page.crafts.heritage': 'Patrimoine Culturel',
    'page.crafts.loading': 'Chargement de nos beaux artisanats...',
    'page.crafts.error': 'Impossible de charger les artisanats',
    'page.crafts.tryAgain': 'Veuillez réessayer plus tard',
    'page.crafts.noCrafts': 'Aucun artisanat disponible',
    'page.crafts.checkBack': 'Revenez plus tard pour notre belle collection d\'artisanats.',
    'page.crafts.explore': 'Explorer les Artisanats',
    'page.crafts.traditional': 'Traditionnel',
    'page.crafts.preserving': 'Préserver le Patrimoine Culturel',
    'page.crafts.preservingText': 'Chaque artisanat représente des siècles de tradition, de compétence et d\'identité culturelle. En soutenant nos artisans, vous aidez à préserver ces techniques inestimables pour les générations futures.',
    'page.crafts.skilledArtisans': 'Artisans Qualifiés',
    'page.crafts.yearsOfTradition': 'Années de Tradition',
    'page.crafts.authenticHandmade': 'Fait Main Authentique',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Negozio',
    'nav.crafts': 'I Nostri Artigianati',
    'nav.stories': 'Storie',
    'nav.gifts': 'Idee Regalo',
    'nav.sustainability': 'Sostenibilità',
    'nav.csr': 'CSR',
    'nav.about': 'Chi siamo',
    'nav.contact': 'Contatto',
    'nav.cart': 'Carrello',
    'nav.signin': 'Accedi / Registrati',
    'nav.account': 'Account',
    'nav.welcome': 'Benvenuto',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.tryAgain': 'Riprova',
    'common.readMore': 'Leggi di più',
    'common.learnMore': 'Scopri di più',
    'common.viewAll': 'Vedi tutto',
    'common.shopNow': 'Acquista ora',
    'common.addToCart': 'Aggiungi al carrello',
    'common.buyNow': 'Compra ora',
    'common.contactUs': 'Contattaci',
    
    // Pages
    'page.stories.title': 'Storie di Artigiani',
    'page.stories.subtitle': 'Incontra gli artigiani talentuosi che preservano le tradizioni africane attraverso la loro arte',
    'page.stories.noStories': 'Nessuna storia disponibile',
    'page.stories.checkBack': 'Torna più tardi per storie ispiratrici di artigiani.',
    'page.stories.shareStory': 'Condividi la tua storia',
    'page.stories.shareDescription': 'Sei un artigiano qualificato con una storia da raccontare? Ci piacerebbe presentare il tuo mestiere e condividere il tuo viaggio con la nostra comunità di appassionati d\'arte.',
    'page.stories.browseCrafts': 'Sfoglia artigianati',
    'page.stories.readFullStory': 'Leggi la storia completa',
    
    'page.contact.title': 'Contattaci',
    'page.contact.subtitle': 'Mettiti in contatto con noi per domande sui nostri artigianati, ordini personalizzati o collaborazioni con artigiani',
    'page.contact.sendMessage': 'Inviaci un messaggio',
    'page.contact.getInTouch': 'Mettiti in contatto',
    'page.contact.fullName': 'Nome completo',
    'page.contact.emailAddress': 'Indirizzo email',
    'page.contact.subject': 'Oggetto',
    'page.contact.message': 'Messaggio',
    'page.contact.sendButton': 'Invia messaggio',
    'page.contact.location': 'La nostra posizione',
    'page.contact.phone': 'Numero di telefono',
    'page.contact.email': 'Indirizzo email',
    'page.contact.hours': 'Orari di lavoro',
    'page.contact.visitWorkshop': 'Visita il nostro laboratorio',
    'page.contact.scheduleVisit': 'Programma una visita',
    
    'page.about.title': 'Chi Siamo - Things From Africa',
    'page.about.subtitle': 'Preservando tradizioni, potenziando artigiani e condividendo la bellezza dell\'Africa con il mondo',
    'page.about.mission': 'La Nostra Missione',
    'page.about.missionText1': 'Ci dedichiamo a preservare il ricco patrimonio culturale dell\'Africa attraverso prodotti artigianali autentici. La nostra missione è connettere artigiani qualificati con mercati globali mantenendo l\'integrità dell\'artigianato tradizionale.',
    'page.about.missionText2': 'Ogni acquisto supporta le comunità locali e aiuta a preservare tecniche secolari tramandate di generazione in generazione.',
    'page.about.meetArtisans': 'Incontra i Nostri Artigiani',
    'page.about.values': 'I Nostri Valori',
    'page.about.authenticity': 'Autenticità',
    'page.about.quality': 'Qualità',
    'page.about.community': 'Comunità',
    'page.about.sustainability': 'Sostenibilità',
    'page.about.story': 'La Nostra Storia',
    'page.about.storyText1': 'Fondata nel 2015, Malawi Crafts è iniziata come una piccola iniziativa per aiutare gli artigiani locali a raggiungere i mercati internazionali. Quello che è iniziato come un progetto di passione è cresciuto in una piattaforma fiorente che mostra l\'incredibile talento e creatività degli artigiani malawiani.',
    'page.about.storyText2': 'Oggi lavoriamo con oltre 200 artigiani in tutto il Malawi, dagli intagliatori di legno di Lilongwe ai tessitori di cesti delle regioni settentrionali. Ogni pezzo racconta una storia di abilità, tradizione e la cultura vibrante del "Cuore Caldo dell\'Africa".',
    'page.about.storyText3': 'Crediamo che condividendo questi bellissimi artigianati con il mondo, non stiamo solo vendendo prodotti – stiamo costruendo ponti tra culture e creando mezzi di sostentamento sostenibili per artigiani talentuosi.',
    'page.about.communityImpact': 'Impatto Comunitario',
    'page.about.communityText': 'Supportare famiglie e preservare competenze tradizionali nelle comunità rurali dell\'Africa.',
    'page.about.globalReach': 'Portata Globale',
    'page.about.globalText': 'Connettere artigiani africani con clienti in tutto il mondo, condividendo la nostra cultura globalmente.',
    'page.about.sustainableFuture': 'Futuro Sostenibile',
    'page.about.sustainableText': 'Creare opportunità economiche durature rispettando il nostro ambiente e le nostre tradizioni.',
    'page.about.joinJourney': 'Unisciti al Nostro Viaggio',
    'page.about.joinText': 'Diventa parte della nostra storia supportando l\'artigianato africano autentico. Ogni acquisto fa la differenza nel preservare il nostro patrimonio culturale e supportare le comunità artigianali.',
    'page.about.shopCrafts': 'Acquista i Nostri Artigianati',
    'page.about.learnMore': 'Scopri di Più',
    'page.about.artisans': 'Artigiani',
    'page.about.regions': 'Regioni',
    'page.about.founded': 'Fondata',
    'page.about.customers': 'Clienti Felici',
    
    'page.crafts.title': 'I Nostri Artigianati Tradizionali',
    'page.crafts.subtitle': 'Scopri il ricco patrimonio dell\'artigianato africano attraverso la nostra diversa collezione di arti tradizionali',
    'page.crafts.authentic': 'Fatto a Mano Autentico',
    'page.crafts.sustainable': 'Materiali Sostenibili',
    'page.crafts.heritage': 'Patrimonio Culturale',
    'page.crafts.loading': 'Caricamento dei nostri bellissimi artigianati...',
    'page.crafts.error': 'Impossibile caricare gli artigianati',
    'page.crafts.tryAgain': 'Riprova più tardi',
    'page.crafts.noCrafts': 'Nessun artigianato disponibile',
    'page.crafts.checkBack': 'Torna più tardi per la nostra bella collezione di artigianati.',
    'page.crafts.explore': 'Esplora Artigianati',
    'page.crafts.traditional': 'Tradizionale',
    'page.crafts.preserving': 'Preservare il Patrimonio Culturale',
    'page.crafts.preservingText': 'Ogni artigianato rappresenta secoli di tradizione, abilità e identità culturale. Supportando i nostri artigiani, aiuti a preservare queste tecniche inestimabili per le generazioni future.',
    'page.crafts.skilledArtisans': 'Artigiani Qualificati',
    'page.crafts.yearsOfTradition': 'Anni di Tradizione',
    'page.crafts.authenticHandmade': 'Fatto a Mano Autentico',
  },
  sw: {
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.shop': 'Duka',
    'nav.crafts': 'Sanaa Zetu',
    'nav.stories': 'Hadithi',
    'nav.gifts': 'Mawazo ya Zawadi',
    'nav.sustainability': 'Uendelevu',
    'nav.csr': 'CSR',
    'nav.about': 'Kuhusu',
    'nav.contact': 'Mawasiliano',
    'nav.cart': 'Kikapu',
    'nav.signin': 'Ingia / Jisajili',
    'nav.account': 'Akaunti',
    'nav.welcome': 'Karibu',
    
    // Common
    'common.loading': 'Inapakia...',
    'common.error': 'Hitilafu',
    'common.tryAgain': 'Jaribu tena',
    'common.readMore': 'Soma zaidi',
    'common.learnMore': 'Jifunze zaidi',
    'common.viewAll': 'Ona yote',
    'common.shopNow': 'Nunua sasa',
    'common.addToCart': 'Ongeza kwenye kikapu',
    'common.buyNow': 'Nunua sasa',
    'common.contactUs': 'Wasiliana nasi',
    
    // Pages
    'page.stories.title': 'Hadithi za Mafundi',
    'page.stories.subtitle': 'Kutana na mafundi wenye talanta wanaohifadhi mila za Kiafrika kupitia sanaa zao',
    'page.stories.noStories': 'Hakuna hadithi zinazopatikana',
    'page.stories.checkBack': 'Rudi baadaye kwa hadithi za kuvutia za mafundi.',
    'page.stories.shareStory': 'Shiriki hadithi yako',
    'page.stories.shareDescription': 'Je, wewe ni fundi mwenye ujuzi na hadithi ya kusimulia? Tungependa kuonyesha sanaa yako na kushiriki safari yako na jumuiya yetu ya wapenda sanaa.',
    'page.stories.browseCrafts': 'Vinjari sanaa',
    'page.stories.readFullStory': 'Soma hadithi kamili',
    
    'page.contact.title': 'Wasiliana nasi',
    'page.contact.subtitle': 'Wasiliana nasi kwa maswali kuhusu sanaa zetu, maagizo maalum au ushirikiano wa mafundi',
    'page.contact.sendMessage': 'Tutumie ujumbe',
    'page.contact.getInTouch': 'Wasiliana',
    'page.contact.fullName': 'Jina kamili',
    'page.contact.emailAddress': 'Anwani ya barua pepe',
    'page.contact.subject': 'Mada',
    'page.contact.message': 'Ujumbe',
    'page.contact.sendButton': 'Tuma ujumbe',
    'page.contact.location': 'Mahali tulipo',
    'page.contact.phone': 'Nambari ya simu',
    'page.contact.email': 'Anwani ya barua pepe',
    'page.contact.hours': 'Masaa ya biashara',
    'page.contact.visitWorkshop': 'Tembelea warsha yetu',
    'page.contact.scheduleVisit': 'Panga ziara',
    
    'page.about.title': 'Kuhusu Things From Africa',
    'page.about.subtitle': 'Kuhifadhi mila, kuwawezesha mafundi, na kushiriki uzuri wa Afrika na ulimwengu',
    'page.about.mission': 'Dhamira Yetu',
    'page.about.missionText1': 'Tumejitolea kuhifadhi utamaduni mkuu wa Afrika kupitia bidhaa za mikono halisi. Dhamira yetu ni kuunganisha mafundi wenye ujuzi na masoko ya kimataifa huku tukihifadhi uongozi wa ufundi wa jadi.',
    'page.about.missionText2': 'Kila ununuzi unaunga mkono jamii za mitaani na kusaidia kuhifadhi mbinu za karne nyingi zilizopitishwa kizazi hadi kizazi.',
    'page.about.meetArtisans': 'Kutana na Mafundi Wetu',
    'page.about.values': 'Maadili Yetu',
    'page.about.authenticity': 'Uhalisi',
    'page.about.quality': 'Ubora',
    'page.about.community': 'Jamii',
    'page.about.sustainability': 'Uendelevu',
    'page.about.story': 'Hadithi Yetu',
    'page.about.storyText1': 'Ilianzishwa mnamo 2015, Malawi Crafts ilianza kama mpango mdogo wa kusaidia mafundi wa mitaani kufikia masoko ya kimataifa. Kile kilichoanza kama mradi wa shauku kimekua kuwa jukwaa lenye mafanikio linaloonyesha talanta na ubunifu wa ajabu wa mafundi wa Malawi.',
    'page.about.storyText2': 'Leo tunafanya kazi na mafundi zaidi ya 200 kote Malawi, kutoka wachongaji wa mbao huko Lilongwe hadi wasokaji wa vikapu katika mikoa ya kaskazini. Kila kipande kinasimulia hadithi ya ujuzi, utamaduni, na utamaduni mkuu wa "Moyo wa Joto wa Afrika".',
    'page.about.storyText3': 'Tunaamini kwamba kwa kushiriki sanaa hizi nzuri na ulimwengu, hatuuzi tu bidhaa – tunajenga madaraja kati ya tamaduni na kuunda maisha endelevu kwa mafundi wenye talanta.',
    'page.about.communityImpact': 'Athari za Kijamii',
    'page.about.communityText': 'Kuunga mkono familia na kuhifadhi ujuzi wa jadi katika jamii za vijijini Afrika.',
    'page.about.globalReach': 'Ufikaji wa Kimataifa',
    'page.about.globalText': 'Kuunganisha mafundi wa Afrika na wateja duniani kote, kushiriki utamaduni wetu kimataifa.',
    'page.about.sustainableFuture': 'Mustakabali Endelevu',
    'page.about.sustainableText': 'Kuunda fursa za kiuchumi za kudumu huku tukiheshimu mazingira yetu na mila zetu.',
    'page.about.joinJourney': 'Jiunge na Safari Yetu',
    'page.about.joinText': 'Kuwa sehemu ya hadithi yetu kwa kuunga mkono ufundi halisi wa Afrika. Kila ununuzi unaleta mabadiliko katika kuhifadhi utamaduni wetu na kuunga mkono jamii za mafundi.',
    'page.about.shopCrafts': 'Nunua Sanaa Zetu',
    'page.about.learnMore': 'Jifunze Zaidi',
    'page.about.artisans': 'Mafundi',
    'page.about.regions': 'Mikoa',
    'page.about.founded': 'Ilianzishwa',
    'page.about.customers': 'Wateja Wenye Furaha',
    
    'page.crafts.title': 'Sanaa Zetu za Jadi',
    'page.crafts.subtitle': 'Gundua utamaduni mkuu wa ufundi wa Afrika kupitia mkusanyiko wetu wa sanaa za jadi',
    'page.crafts.authentic': 'Kimetengenezwa kwa Mikono Halisi',
    'page.crafts.sustainable': 'Vifaa Endelevu',
    'page.crafts.heritage': 'Utamaduni wa Kitamaduni',
    'page.crafts.loading': 'Inapakia sanaa zetu nzuri...',
    'page.crafts.error': 'Imeshindwa kupakia sanaa',
    'page.crafts.tryAgain': 'Tafadhali jaribu tena baadaye',
    'page.crafts.noCrafts': 'Hakuna sanaa zinazopatikana',
    'page.crafts.checkBack': 'Rudi baadaye kwa mkusanyiko wetu mzuri wa sanaa.',
    'page.crafts.explore': 'Chunguza Sanaa',
    'page.crafts.traditional': 'Za Jadi',
    'page.crafts.preserving': 'Kuhifadhi Utamaduni wa Kitamaduni',
    'page.crafts.preservingText': 'Kila sanaa inawakilisha karne za utamaduni, ujuzi na utambulisho wa kitamaduni. Kwa kuunga mkono mafundi wetu, unasaidia kuhifadhi mbinu hizi za thamani kwa vizazi vijavyo.',
    'page.crafts.skilledArtisans': 'Mafundi Wenye Ujuzi',
    'page.crafts.yearsOfTradition': 'Miaka ya Utamaduni',
    'page.crafts.authenticHandmade': 'Kimetengenezwa kwa Mikono Halisi',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.shop': 'Shop',
    'nav.crafts': 'Unser Handwerk',
    'nav.stories': 'Geschichten',
    'nav.gifts': 'Geschenkideen',
    'nav.sustainability': 'Nachhaltigkeit',
    'nav.csr': 'CSR',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.cart': 'Warenkorb',
    'nav.signin': 'Anmelden / Registrieren',
    'nav.account': 'Konto',
    'nav.welcome': 'Willkommen',
    
    // Common
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.tryAgain': 'Erneut versuchen',
    'common.readMore': 'Mehr lesen',
    'common.learnMore': 'Mehr erfahren',
    'common.viewAll': 'Alle anzeigen',
    'common.shopNow': 'Jetzt einkaufen',
    'common.addToCart': 'In den Warenkorb',
    'common.buyNow': 'Jetzt kaufen',
    'common.contactUs': 'Kontaktieren Sie uns',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.shop': 'Loja',
    'nav.crafts': 'Nossos Artesanatos',
    'nav.stories': 'Histórias',
    'nav.gifts': 'Ideias de Presentes',
    'nav.sustainability': 'Sustentabilidade',
    'nav.csr': 'RSC',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.cart': 'Carrinho',
    'nav.signin': 'Entrar / Registrar',
    'nav.account': 'Conta',
    'nav.welcome': 'Bem-vindo',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.tryAgain': 'Tentar novamente',
    'common.readMore': 'Ler mais',
    'common.learnMore': 'Saber mais',
    'common.viewAll': 'Ver tudo',
    'common.shopNow': 'Comprar agora',
    'common.addToCart': 'Adicionar ao carrinho',
    'common.buyNow': 'Comprar agora',
    'common.contactUs': 'Entre em contato',
  },
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Winkel',
    'nav.crafts': 'Ons Handwerk',
    'nav.stories': 'Verhalen',
    'nav.gifts': 'Cadeau-ideeën',
    'nav.sustainability': 'Duurzaamheid',
    'nav.csr': 'MVO',
    'nav.about': 'Over ons',
    'nav.contact': 'Contact',
    'nav.cart': 'Winkelwagen',
    'nav.signin': 'Inloggen / Registreren',
    'nav.account': 'Account',
    'nav.welcome': 'Welkom',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.tryAgain': 'Opnieuw proberen',
    'common.readMore': 'Meer lezen',
    'common.learnMore': 'Meer leren',
    'common.viewAll': 'Alles bekijken',
    'common.shopNow': 'Nu winkelen',
    'common.addToCart': 'Toevoegen aan winkelwagen',
    'common.buyNow': 'Nu kopen',
    'common.contactUs': 'Neem contact op',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.shop': '商店',
    'nav.crafts': '我们的工艺品',
    'nav.stories': '故事',
    'nav.gifts': '礼品创意',
    'nav.sustainability': '可持续性',
    'nav.csr': '企业社会责任',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.cart': '购物车',
    'nav.signin': '登录 / 注册',
    'nav.account': '账户',
    'nav.welcome': '欢迎',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.tryAgain': '重试',
    'common.readMore': '阅读更多',
    'common.learnMore': '了解更多',
    'common.viewAll': '查看全部',
    'common.shopNow': '立即购买',
    'common.addToCart': '添加到购物车',
    'common.buyNow': '立即购买',
    'common.contactUs': '联系我们',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as Language;
    if (savedLanguage && ['en', 'es', 'fr', 'it', 'sw', 'de', 'pt', 'nl', 'zh'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', language);
  };

  const t = useMemo(() => (key: string): string => {
    return translations[currentLanguage][key] || key;
  }, [currentLanguage]);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};